# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_auto_20170130_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLabel', models.CharField(max_length=250)),
                ('questionNumber', models.DecimalField(decimal_places=2, default='1', max_digits=5)),
                ('surveyTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitepages.Survey')),
            ],
        ),
    ]
