# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitepages', '0006_auto_20170130_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLabel', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('dateSurvCreated', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('numOfQuestions', models.DecimalField(decimal_places=2, default='1', max_digits=5)),
                ('numOfTimesCompleted', models.DecimalField(decimal_places=2, default='1', max_digits=5)),
            ],
        ),
    ]
