# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0007_question_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
