# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0008_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
