# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLabel', models.CharField(max_length=250)),
                ('sName', models.CharField(default='survey', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='question',
        ),
        migrations.AddField(
            model_name='post',
            name='numOfQuestions',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='post',
            name='numOfTimesCompleted',
            field=models.IntegerField(default='1'),
        ),
    ]
