# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numOfQuestions',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=5),
        ),
        migrations.AddField(
            model_name='post',
            name='numOfTimesCompleted',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=5),
        ),
    ]
