# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170131_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sName',
            new_name='surveybelongto',
        ),
    ]
