# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170131_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.IntegerField(default='1'),
        ),
    ]
