# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='surveyName',
            field=models.ForeignKey(default='survey', on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
