# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_question_surveyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='surveyName',
            field=models.CharField(max_length=250),
        ),
    ]
