# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170202_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.IntegerField(default='1'),
        ),
    ]
