# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_answers_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answerID',
            new_name='questionID',
        ),
        migrations.AddField(
            model_name='answers',
            name='answerLabel',
            field=models.CharField(default='answer', max_length=250),
        ),
        migrations.AddField(
            model_name='answers',
            name='questionTitle',
            field=models.CharField(default='question', max_length=250),
        ),
        migrations.AddField(
            model_name='answers',
            name='surveyName',
            field=models.CharField(default='survey', max_length=250),
        ),
    ]
