# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20170202_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='questionID',
            new_name='answerID',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answerLabel',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='questionTitle',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='surveyName',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ManyToManyField(to='posts.Question'),
        ),
    ]
