# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170202_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
