# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20170203_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLabel', models.CharField(max_length=250)),
                ('surveybelongto', models.CharField(default='survey', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='answerLabel',
            field=models.CharField(default='answer', max_length=250),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answerID',
            field=models.CharField(max_length=250),
        ),
    ]
