# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170203_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='questionNumber',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='answers',
            name='surveyTitle',
            field=models.CharField(default='survey', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.IntegerField(default='1'),
        ),
    ]
