# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170203_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='questionLabel',
            field=models.CharField(default='survey', max_length=250),
        ),
    ]
