# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_question_numberofanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answerCounter',
            field=models.IntegerField(default='0'),
        ),
    ]
