# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_answers_answercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.CharField(default='no', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='privatePasscode',
            field=models.CharField(default='passcode', max_length=250),
        ),
    ]
