# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20170228_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='private',
        ),
        migrations.RemoveField(
            model_name='post',
            name='privatePasscode',
        ),
    ]
