# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20170301_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.CharField(default='no', max_length=250),
        ),
    ]
