# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20170301_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='private',
        ),
        migrations.RemoveField(
            model_name='post',
            name='privatePasscode',
        ),
    ]
