# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20170301_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='privateCode',
            field=models.CharField(max_length=250),
        ),
    ]
