# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20170301_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='passcode',
            field=models.CharField(default='passcode', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.CharField(default='no', max_length=250),
        ),
    ]
