# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_remove_post_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='passcode',
        ),
    ]
