# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.CharField(default='code', max_length=250),
        ),
    ]
