# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20170301_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyTitle', models.CharField(default='title', max_length=250)),
                ('question', models.CharField(default='question', max_length=250)),
                ('answer', models.CharField(default='answer', max_length=250)),
            ],
        ),
    ]
