# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_delete_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(default=b'survey', max_length=250)),
                ('question', models.CharField(default=b'question', max_length=250)),
                ('answer', models.CharField(default=b'answer', max_length=250)),
            ],
        ),
    ]
